server {
    listen 10000;

    server_name _;

    root /var/www/public;
    index index.php;

    client_max_body_size 100M;

    include /etc/nginx/mime.types;

    # PDF.js module worker
    location ~* \.mjs$ {
        default_type application/javascript;
        try_files $uri =404;
    }

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        fastcgi_pass 127.0.0.1:9000;
        fastcgi_index index.php;

        include fastcgi_params;

        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;

        fastcgi_param HTTPS on;
        fastcgi_param REQUEST_SCHEME https;

        fastcgi_param HTTP_HOST $http_host;
        fastcgi_param SERVER_NAME $host;
        fastcgi_param SERVER_PORT 443;

        fastcgi_buffer_size 32k;
        fastcgi_buffers 8 32k;
        fastcgi_busy_buffers_size 64k;
        fastcgi_read_timeout 120;
    }
}
